name: CI/CD Workflow

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: macos

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install
          # Add build commands here
          # Add test commands here
      - name: Build
        run: |
          npm run build 
          # Add build commands here
          # Add test commands here

      - name: Run tests
        run: |
          npm run test
          # Add deployment commands here

